### ISSUE TITLE
spawn ps ENOENT

### ISSUE THREAD

**Issue by RezaErfani67** [vercel/ncc#491] opened 2019-12-05 06:37 UTC
cought exception with node 12.13.1
![image](https://user-images.githubusercontent.com/24381986/70210064-027bb500-1747-11ea-8082-e21c0df43e3d.png)

**Comment by styfle** [comment] 2021-09-09 00:49
Closing since there are no steps to reproduce

**Closed by styfle** 2021-09-09 00:49 UTC
