### ISSUE TITLE
TypeError: this.extractCredentials is not a function

### ISSUE THREAD

**Issue by therk** [vercel/ncc#533] opened 2020-04-27 21:03 UTC
I get a failure when I run ncc with aws-sdk module:
ncc run src/server.ts        
ncc: Version 0.22.1
ncc: Compiling file index.js
ncc: Using typescript@3.8.3 (local user-provided)
ncc: Ignoring build of uglify-js, as it is not statically analyzable. Build with "--external uglify-js" if this package is needed.
    0kB  templates/welcomeEmail/html.ejs
    0kB  templates/welcomeEmail/subject.ejs
    2kB  template.pug
   25kB  xdg-open
   66kB  lib/binding/napi-v3/bcrypt_lib.node
  121kB  sourcemap-register.js
  139kB  domprops.json
  410kB  code-points.mem
31000kB  index.js
29585kB  index.js.map
31763kB  [50643ms] - ncc 0.22.1

/private/var/folders/h4/qslrw_yn4wg7gf2k9ht8hqj80000gn/T/node_modules/aws-sdk/lib/config.js:445
    options = this.extractCredentials(options);
^
TypeError: this.extractCredentials is not a function
    at update (/private/var/folders/h4/qslrw_yn4wg7gf2k9ht8hqj80000gn/T/node_modules/aws-sdk/lib/config.js:445:1)
    at Module.<anonymous> (/private/var/folders/h4/qslrw_yn4wg7gf2k9ht8hqj80000gn/T/src/modules/mailer/nodemailer.ts:7:18)
    at __webpack_require__ (/webpack/bootstrap:19:1)
    at startup (/webpack/bootstrap:34:1)
    at /webpack/bootstrap:40:1
    at Object.<anonymous> (/private/var/folders/h4/qslrw_yn4wg7gf2k9ht8hqj80000gn/T/b262c2d89e2d068366c626cb875c97ed/index.js:46:10)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by jeff-block** [comment] 2021-04-20 02:58
+1

**Comment by styfle** [comment] 2023-10-18 21:36
Closing since the content of `src/server.ts` was not provided and therefore can't be reproduced

**Closed by styfle** 2023-10-18 21:36 UTC
