### ISSUE TITLE
__dirname is not defined in ES module scope (when using commonjs dependency from es module package)

### ISSUE THREAD

**Issue by BCaspari** [vercel/ncc#895] opened 2022-03-24 14:29 UTC
In a project with` "type": "module"` in the package.json that uses the vm2 package (or any other package that uses the `__dirname `or `__filename `variables), the generated output throws an Error: 

```
`(function(global) {"use strict"; const exports = {};${fs.readFileSync(`${__dirname}/bridge.js`, 'utf8')}\nreturn exports;})`);
                                                                                
ReferenceError: __dirname is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and 'C:\ph\ProcessHub_master\app\distncc\package.json' contains "type": "module". To 
treat it as a CommonJS script, rename it to use the '.cjs' file extension.
```
The project runs without problems when starting with node. I think __dirname and __filename should be removed from the ncc build?

**Comment by styfle** [comment] 2022-04-01 21:28
Sounds similar to #749

**Comment by styfle** [comment] 2024-02-12 13:46
Closing as a duplicate of https://github.com/vercel/ncc/issues/749

**Closed by styfle** 2024-02-12 13:46 UTC
