### ISSUE TITLE
esModuleInterlop not used in secondary file

### ISSUE THREAD

**Issue by EndBug** [vercel/ncc#621] opened 2020-12-06 16:55 UTC
My code has two files, that look like this:

```ts
// main.ts
import path from 'path' // This uses esModuleInterlop, and doesn't cause issues
import { setOutput } from './util'

path.normalize('') // OK
setOutput('a', 'b') // Cannot read property 'setOutput' of undefined
```

```ts
// util.ts
import core from '@actions/core' // This should use esModuleInterlop too, but I get an error

export function setOutput(a, b) {
  return core.setOutput(a, b)
}
```

The error I'm showing in the code ("Cannot read property 'setOuput' of undefined") only happens when I use the build, there are no compile errors. Since this is the code of a GitHub Action, I have no way of running this code locally before NCC compiles it.

I know that the issue is with `esModuleInterlop` because I solved it by using `import * as core from '@actions/core'`

Do you have any clue on what could I have been doing wrong?

**Comment by guybedford** [comment] 2021-03-19 14:46
This seems like a duplicate of https://github.com/vercel/ncc/issues/626, will address this there.

**Closed by guybedford** 2021-03-19 14:46 UTC
