### ISSUE TITLE
Build runs indefinitely when using Minify option

### ISSUE THREAD

**Issue by Djiit** [vercel/ncc#526] opened 2020-03-28 09:36 UTC
Hi 👋 ,

Since I upgraded to 0.22.0, all my local + heroku builds are stuck and ends up in timeouts.
I'll try to make a reproducible example in the weekend.

Saw that using Node 12 / Node 13 and TS 3.8.3 on my macos laptop and the heroku-18 stack.

**Comment by cdupuis** [comment] 2020-09-03 09:54
I'm seeing the same with latest version. I narrowed it down to using the source-map and minify options. When those two are removed, the build finishes as usual. Not sure that's the  same for @Djiit?

**Comment by Djiit** [comment] 2020-09-05 08:53
Hey

It's now working for me with v0.24, with and without the `-s`options. Not sure if we hit the same behavior here :/.

```
$ ncc build src/index.ts -m
ncc: Version 0.24.0
ncc: Compiling file index.js
ncc: Using typescript@3.9.7 (local user-provided)
  67kB  dist/socket.io.js
 434kB  dist/socket.io.js.map
6176kB  dist/index.js
6677kB  [34972ms] - ncc 0.24.0

$ ncc build src/index.ts -m -s
ncc: Version 0.24.0
ncc: Compiling file index.js
ncc: Using typescript@3.9.7 (local user-provided)
  67kB  dist/socket.io.js
 122kB  dist/sourcemap-register.js
 434kB  dist/socket.io.js.map
6176kB  dist/index.js
21390kB  dist/index.js.map
6799kB  [43158ms] - ncc 0.24.0
```

I'm going to close this one if you don't mind.

**Comment by Djiit** [comment] 2020-09-07 09:03
Meh, nevermind, I can still see this and @cdupuis is right, it works when I remove the -m option.

**Comment by styfle** [comment] 2023-10-18 21:35
Closing since there are no steps to reproduce the issue

**Closed by styfle** 2023-10-18 21:35 UTC
