### ISSUE TITLE
打包之后在linux系统下无法运行

### ISSUE THREAD

**Issue by LH-hua** [vercel/ncc#1185] opened 2024-04-29 07:16 UTC
#  打包之后在linux系统下无法运行

以下是错误提示
[root@localhost dist]# ls
assets  Comismsh.ttf  index.js  lib
[root@localhost dist]# node index.js
node:internal/modules/cjs/loader:1340
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /var/local/dist/lib/binding/napi-v3/bcrypt_lib.node: invalid ELF header
    at Module._extensions..node (node:internal/modules/cjs/loader:1340:18)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at 67848 (/var/local/dist/index.js:222590:18)
    at __nccwpck_require__ (/var/local/dist/index.js:229920:43)
    at 76017 (/var/local/dist/index.js:23533:16)
    at __nccwpck_require__ (/var/local/dist/index.js:229920:43)
    at 50538 (/var/local/dist/index.js:222296:16) {
  code: 'ERR_DLOPEN_FAILED'
}

系统:centOS7
node: v18.16.1

**Comment by LH-hua** [comment] 2024-04-29 07:19
bcrypt_lib.node 文件ELF头部，无效或者加载错误
在windows系统正常运行

**Comment by styfle** [comment] 2024-04-29 18:15
This error is unlikely to be caused by ncc since `.node` files are not modified

Closing since there is nothing actionable here without steps to reproduce the issue.

**Closed by styfle** 2024-04-29 18:15 UTC
