### ISSUE TITLE
Compilation result difference on different operation systems

### ISSUE THREAD

**Issue by IvanZosimov** [vercel/ncc#1057] opened 2023-03-23 13:29 UTC
**Description**:
Hi 👋 , in https://github.com/actions/setup-java repo we faced an odd issue. The result output of the [`build`](https://github.com/actions/setup-java/blob/main/package.json#L8) command is different on Windows and macOS/Linux. Here you can check the output `.js` files:
**Windows**: [windows.zip](https://github.com/vercel/ncc/files/11050976/windows.zip)
**Linux**: [linux.zip](https://github.com/vercel/ncc/files/11050989/linux.zip)
Output of the `git diff` command can be found here: [gitDiff.zip](https://github.com/vercel/ncc/files/11051085/gitDiff.zip)

**Runners specification**:
| Tool| Ubuntu 22.04.1 | Windows 11 |
|--------|--------|--------|
| TS | 4.2.3 | 4.2.3 |
| Node.js | 16.19.0 | 16.19.1 |
| NPM | 8.19.3 | 8.19.3 |
| NCC | 0.33.4 | 0.33.4 |

If you open the `git diff` output you may notice that the innards of these files are identical (same number of lines, same block of code), only structure is different - some blocks of code are shifted.

We don't have such a problem in other repos where we use `ncc`, like https://github.com/actions/setup-node files built on different OS are identical. Could you give us a hint, what we are doing wrong? Can we even expect that the built files should be identical ?

**What have we tried by now**:
1. Updated `ncc` to the latest version -> saw no changes;

**Related issues**:
https://github.com/vercel/ncc/issues/831

**Comment by styfle** [comment] 2023-03-23 13:51
Thanks, this sounds like a duplicate of #831 so I'll close this one.

There's an identical comment here https://github.com/vercel/ncc/issues/831#issuecomment-996707076

I haven't looked into it but feel free to submit a PR if you have a fix 👍

**Closed by styfle** 2023-03-23 13:51 UTC
